[project]
name = "aerodynamics-datasets"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipython>=9.6.0",
]
